version: "2"

services:
  postgres:
    image: swim-postgres
    container_name: s_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_USER=swim
      - DB_PASS=swim
    volumes:
      - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq_amqp10
    build: ./docker/rabbitmq
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 15671:15671
      - 5671:5671
      - 5672:5672
      - 1883:1883
      - 8883:8883
#    volumes:
#      - ${CERTS_DIR}:/certs/
