version: "2"

services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
#    networks:
#      - backend-dev

  rabbitmq:
    image: rabbitmq_amqp10
    build: ./docker/rabbitmq
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "15671:15671"
      - "5671:5671"
      - "5672:5672"
      - "1883:1883"
      - "8883:8883"
    volumes:
      - /secrets/rabbitmq:/certs/
#    networks:
#      - backend-dev

#networks:
#  backend-dev:
#    driver: bridge
