version: "2"

services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - backend

  rabbitmq:
    image: rabbitmq_amqp10
    build: ./docker/rabbitmq
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "15671:15671"
      - "5671:5671"
      - "5672:5672"
      - "1883:1883"
      - "8883:8883"
    volumes:
      - "${CERTS_FOLDER}:/certs/"
    networks:
      - backend

networks:
  backend:
    driver: bridge