name: subscription-manager
dependencies:
- python
- pytest
- pytest-cov
- Flask
- Flask-SQLAlchemy
- SQLAlchemy
- Werkzeug
- pip:
  - connexion[swagger-ui]
  - marshmallow
  - marshmallow-sqlalchemy
  - psycopg2-binary
  - PyJWT
  - git+ssh://git@bitbucket.org/antavelos-eurocontrol/rest-client.git
  - git+ssh://git@bitbucket.org/antavelos-eurocontrol/broker-rest-client.git
